---
- name: Install Docker
  hosts: all
  become: true

  tasks:
  - name: yum utils for docker
    yum: name=yum-utils state=present

  - name: Add docker repo
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Make yum cache
    command: yum makecache fast

  - name: Install Docker-ce
    yum: name=docker-ce state=present

  - name: Set syctl max_map_count for elasticsearch
    sysctl:
      name: vm.max_map_count
      value: 262144
      state: present

# il faut modifier le service avec les options pour elk et faire un syctl reload
  - name: Position docker ulimits for running elasticsearch on Swarm
    lineinfile:
      destfile: /lib/systemd/system/docker.service
      line: 'ExecStart=/usr/bin/dockerd --default-ulimit memlock=-1:-1 --default-ulimit nofile=65536:65536'
      regexp: '^ExecStart=/usr/bin/dockerd'

# On redémarre docker en rechargeant le service pour prendre en compte les options
  - name: Retart docker
    systemd: state=restarted name=docker daemon_reload=yes

# Pas sur que docker compose soit utile ici...
  - name: Install docker compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.12.0-rc2/docker-compose-Linux-x86_64
      dest: /usr/bin/docker-compose
      mode: 0755

- name: Init Swarm master and get worker token
  hosts: node1
  become: true
  vars:
    manager_ip: 192.168.77.21

  tasks:
  - name: test if swarm already init
    shell: >
      docker info | grep "Swarm: active"
    register: swarm_active
    ignore_errors: True

  - name: Init swarm master
    command: docker swarm init --advertise-addr={{ manager_ip }}:2377
    when: swarm_active|failed

  - name: retrieve swarm worker token
    shell: docker swarm join-token -q worker
    register: swarm_worker_token

- name: Join Worker nodes swarm
  hosts: node2,node3
  become: true
  vars:
    manager_ip: 192.168.77.21
    token: "{{ hostvars['node1']['swarm_worker_token']['stdout'] }}"

  tasks:
  - name: test if swarm already init
    shell: >
      docker info | grep "Swarm: active"
    register: swarm_active
    ignore_errors: True
  
  - name: join worker nodes to cluster
    command: docker swarm join
        --token={{ token }}
        {{ manager_ip }}:2377
    when: swarm_active|failed
