---
- name: Install Docker
  hosts: all
  become: true

  tasks:
  - name: yum utils for docker
    yum: name=yum-utils state=present

  - name: Add docker repo
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Make yum cache
    command: yum makecache fast

  - name: Install Docker-ce
    yum: name=docker-ce state=present

  - name: Start docker
    systemd: state=started name=docker

- name: Init Swarm master and get worker token
  hosts: node1
  become: true
  vars:
    manager_ip: 192.168.77.21

  tasks:
  - name: test if swarm already init
    shell: >
      docker info | grep "Swarm: active"
    register: swarm_active
    ignore_errors: True

  - name: Init swarm master
    command: docker swarm init --advertise-addr={{ manager_ip }}:2377
    when: swarm_active|failed

  - name: retrieve swarm worker token
    shell: docker swarm join-token -q worker
    register: swarm_worker_token

- name: Join Worker nodes swarm
  hosts: node2,node3
  become: true
  vars:
    manager_ip: 192.168.77.21
    token: "{{ hostvars['node1']['swarm_worker_token']['stdout'] }}"

  tasks:
  - name: test if swarm already init
    shell: >
      docker info | grep "Swarm: active"
    register: swarm_active
    ignore_errors: True
  
  - name: join worker nodes to cluster
    command: docker swarm join
        --token={{ token }}
        {{ manager_ip }}:2377
    when: swarm_active|failed
