---
- name: Install Dask with conda
  hosts: all
  become: true

  tasks:
  - name: Create user
    user:
      name: daskusr

  - name: download miniconda
    get_url:
      url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      dest: /home/daskusr/Miniconda3-latest-Linux-x86_64.sh
      mode: 0755

  - name: Install miniconda
    command: /home/daskusr/Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda 
    args:
      creates: "$HOME/miniconda"
    become: true
    become_user: daskusr


  - name: Modify bashrc	
    lineinfile:
      destfile: ~/.bashrc
      line: 'export PATH="$HOME/miniconda/bin:$PATH"'
    become: true
    become_user: daskusr

  - name: Create conda environment with dask installed
    shell: source ~/.bashrc && conda create --name dask dask distributed -c conda-forge
    args:
      creates: /home/daskusr/miniconda/envs/dask
    become: true
    become_user: daskusr
 

- name: Start dask scheduler
  hosts: node1
  become: true
  become_user: daskusr

  tasks:
  - name: activate conda env and start scheduler
    shell: source ~/.bashrc && source activate dask && nohup dask-scheduler </dev/null >/home/daskusr/scheduler.out 2>&1 &

 # - name: Start jupyter notebook
 #   command: ??


- name: Start dask workers
  hosts: node2,node3
  become: true
  become_user: daskusr

  tasks:
  - name: Start worker
    shell: cd ~ && source ~/.bashrc && source activate dask && nohup dask-worker 192.168.77.21:8786 </dev/null >/home/daskusr/worker.out 2>&1 &

