version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=10.0.0.3"
      - "network.host=_eth0:ipv4_"
      - "network.publish_host=_eth0:ipv4_"
# Ulimits are currently not being use with docker stack create !!
# Tryning to configure at docker daemon level...
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
# Does not work with swarm
#    cap_add:
#      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
    deploy:
      mode: global
      resources:
        limits:
          cpus: '1.0'
          memory: 2g
  
volumes:
  esdata:
    driver: local

networks:
  esnet:
